### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by heikamal**
Changed the language of the readme-file from finnish to english as requested

### CODE REVIEW

**Review by ComplexMonkeys — APPROVED** [review]
Looks good to me

**Comment by Kimboooo** [comment]
AWESOME SAUCE

**Review by Kimboooo — APPROVED** [review]
TÄSSÄ OIS PYSTYNY ERIKSEEN KOMMENTOIMAAN

**Review by Potakka — COMMENTED** [review]
Nonni 👍

**Review by Potakka — COMMENTED** [review]
👍

**Pull request merged**
